from __future__ import annotations

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from industrial_defect.io import read_csv  # noqa: E402


def to_float(row: dict[str, str], key: str) -> float:
    value = row.get(key, "")
    return float(value) if value not in {"", None} else 0.0


def format_metric(value: float) -> str:
    return f"{value:.4f}"


def write_dashboard(summary_path: Path, class_path: Path, output_path: Path) -> None:
    summary_rows = read_csv(summary_path)
    class_rows = read_csv(class_path)
    if not summary_rows:
        raise ValueError(f"No summary rows found in {summary_path.as_posix()}")

    best_rows = [row for row in summary_rows if row["role"] in {"overall_best", "class_specialist", "diagnostic_tradeoff"}]
    stage_rows = sorted(summary_rows, key=lambda row: (row["category"], row["stage"], row["experiment_name"]))

    lines = [
        "# Final Results Dashboard",
        "",
        "Generated by `scripts/14_generate_final_dashboard.py`.",
        "",
        "## Recommended Models",
        "",
        "| category | experiment | role | pixel_f1 | best_pixel_f1 | image_f1 |",
        "| --- | --- | --- | ---: | ---: | ---: |",
    ]
    for row in best_rows:
        lines.append(
            "| {category} | {name} | {role} | {pixel_f1} | {best_pixel_f1} | {image_f1} |".format(
                category=row["category"],
                name=row["experiment_name"],
                role=row["role"],
                pixel_f1=format_metric(to_float(row, "pixel_f1")),
                best_pixel_f1=format_metric(to_float(row, "best_pixel_f1")),
                image_f1=format_metric(to_float(row, "image_f1")),
            )
        )

    lines.extend([
        "",
        "## Experiment Progression",
        "",
        "| category | stage | experiment | role | pixel_precision | pixel_recall | pixel_f1 | image_f1 |",
        "| --- | --- | --- | --- | ---: | ---: | ---: | ---: |",
    ])
    for row in stage_rows:
        lines.append(
            "| {category} | {stage} | {name} | {role} | {precision} | {recall} | {f1} | {image_f1} |".format(
                category=row["category"],
                stage=row["stage"],
                name=row["experiment_name"],
                role=row["role"],
                precision=format_metric(to_float(row, "pixel_precision")),
                recall=format_metric(to_float(row, "pixel_recall")),
                f1=format_metric(to_float(row, "pixel_f1")),
                image_f1=format_metric(to_float(row, "image_f1")),
            )
        )

    highlight_keys = {
        ("tile", "gray_stroke"),
        ("tile", "crack"),
        ("wood", "scratch"),
        ("leather", "cut"),
        ("leather", "fold"),
    }
    lines.extend([
        "",
        "## Key Class Repairs",
        "",
        "| category | experiment | defect_type | role | mean_dice | mean_recall |",
        "| --- | --- | --- | --- | ---: | ---: |",
    ])
    for row in class_rows:
        key = (row["category"], row["defect_type"])
        if key not in highlight_keys:
            continue
        if row["role"] not in {"diagnostic_baseline", "generalization_baseline", "overall_best", "class_specialist", "diagnostic_tradeoff"}:
            continue
        lines.append(
            "| {category} | {name} | {defect} | {role} | {dice} | {recall} |".format(
                category=row["category"],
                name=row["experiment_name"],
                defect=row["defect_type"],
                role=row["role"],
                dice=format_metric(to_float(row, "mean_dice")),
                recall=format_metric(to_float(row, "mean_recall")),
            )
        )

    lines.extend([
        "",
        "## Reading Guide",
        "",
        "- Stage 6 is the tile overall recommendation.",
        "- Stage 7 is a tile crack specialist, not the overall tile winner.",
        "- Stage 9 is the wood overall recommendation.",
        "- Stage 11 is the leather overall recommendation.",
        "- Stage 12 is a fold recall tradeoff experiment, not the leather overall winner.",
    ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    output_dir = Path("outputs") / "final_report"
    write_dashboard(
        output_dir / "final_metrics_summary.csv",
        output_dir / "final_class_metrics.csv",
        output_dir / "final_results_dashboard.md",
    )
    print(f"Dashboard written to {(output_dir / 'final_results_dashboard.md').as_posix()}")


if __name__ == "__main__":
    main()

