from __future__ import annotations

import argparse
import importlib
import os
import platform
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from industrial_defect.config import defect_types_for_category, supported_categories  # noqa: E402
from industrial_defect.final_results import FINAL_EXPERIMENTS  # noqa: E402
from industrial_defect.io import list_images, read_json  # noqa: E402


REQUIRED_OUTPUTS = [
    Path("outputs/final_report/final_metrics_summary.csv"),
    Path("outputs/final_report/final_class_metrics.csv"),
    Path("outputs/final_report/final_experiment_timeline.md"),
    Path("docs/final-project-summary.md"),
    Path("docs/interview-talking-points.md"),
]

OPTIONAL_IMPORTS = [
    "numpy",
    "PIL",
    "pandas",
    "torch",
    "torchvision",
    "diffusers",
    "transformers",
]


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Check final project reproducibility prerequisites without retraining.")
    parser.add_argument(
        "--data-root",
        type=Path,
        default=Path(os.environ["DATA_ROOT"]) if os.environ.get("DATA_ROOT") else None,
        help="MVTec AD root. Defaults to DATA_ROOT if set.",
    )
    parser.add_argument("--output-dir", type=Path, default=Path("outputs") / "final_report")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Exit non-zero when training packages or dataset checks fail. Collect-only checks are non-strict by default.",
    )
    return parser.parse_args(argv)


def status_mark(ok: bool) -> str:
    return "PASS" if ok else "FAIL"


def check_import(module_name: str) -> tuple[bool, str]:
    try:
        module = importlib.import_module(module_name)
    except Exception as exc:  # pragma: no cover - diagnostic path
        return False, str(exc)
    version = getattr(module, "__version__", "")
    return True, str(version)


def check_metric_file(path: Path) -> tuple[bool, str]:
    if not path.exists():
        return False, "missing"
    try:
        metrics = read_json(path)
    except Exception as exc:
        return False, f"invalid json: {exc}"
    required = ["pixel_precision", "pixel_recall", "pixel_f1", "best_pixel_f1", "image_f1", "class_metrics"]
    missing = [key for key in required if key not in metrics]
    if missing:
        return False, f"missing keys: {', '.join(missing)}"
    return True, "ok"


def build_report(args: argparse.Namespace) -> tuple[str, bool]:
    lines: list[str] = [
        "# Reproduction Check",
        "",
        "Generated by `scripts/14_reproduction_check.py`.",
        "",
        "## Runtime",
        "",
        f"- Python: `{sys.version.split()[0]}`",
        f"- Platform: `{platform.platform()}`",
        "- Repository root: `.`",
        "",
        "## Python Packages",
        "",
        "| package | status | version / message |",
        "| --- | --- | --- |",
    ]

    all_required_ok = True
    for module_name in OPTIONAL_IMPORTS:
        ok, detail = check_import(module_name)
        lines.append(f"| `{module_name}` | {status_mark(ok)} | `{detail}` |")
        if args.strict and not ok:
            all_required_ok = False

    lines.extend([
        "",
        "## Final Result Files",
        "",
        "| path | status | note |",
        "| --- | --- | --- |",
    ])
    for path in REQUIRED_OUTPUTS:
        ok = path.exists()
        lines.append(f"| `{path.as_posix()}` | {status_mark(ok)} | {'ok' if ok else 'missing'} |")
        all_required_ok = all_required_ok and ok

    lines.extend([
        "",
        "## Metrics JSON Files",
        "",
        "| experiment | role | path | status | note |",
        "| --- | --- | --- | --- | --- |",
    ])
    for experiment in FINAL_EXPERIMENTS:
        metrics_path = Path(experiment["metrics_path"])
        ok, detail = check_metric_file(metrics_path)
        lines.append(
            f"| {experiment['name']} | {experiment['role']} | `{metrics_path.as_posix()}` | {status_mark(ok)} | {detail} |"
        )
        all_required_ok = all_required_ok and ok

    dataset_ok = True
    lines.extend([
        "",
        "## Dataset Check",
        "",
    ])
    if args.data_root is None:
        dataset_ok = False
        lines.append("`DATA_ROOT` is not set. Set it before regenerating data or retraining models.")
    else:
        data_root = args.data_root
        lines.append("Data root: configured.")
        lines.extend([
            "",
            "| category | train/good | test/good | defect folders | status |",
            "| --- | ---: | ---: | --- | --- |",
        ])
        for category in supported_categories():
            category_root = data_root / category
            train_good_count = len(list_images(category_root / "train" / "good"))
            test_good_count = len(list_images(category_root / "test" / "good"))
            missing_defects = [
                defect_type for defect_type in defect_types_for_category(category)
                if not (category_root / "test" / defect_type).exists()
            ]
            ok = category_root.exists() and train_good_count > 0 and test_good_count > 0 and not missing_defects
            dataset_ok = dataset_ok and ok
            defect_note = "ok" if not missing_defects else "missing: " + ", ".join(missing_defects)
            lines.append(
                f"| {category} | {train_good_count} | {test_good_count} | {defect_note} | {status_mark(ok)} |"
            )

    lines.extend([
        "",
        "## Verdict",
        "",
    ])
    strict_ok = all_required_ok and (dataset_ok or not args.strict)
    if strict_ok:
        lines.append("Core reproducibility files are present. The project is ready for collect-only reproduction.")
        if not dataset_ok:
            lines.append("")
            lines.append("Dataset checks were not required because `--strict` was not used.")
    else:
        lines.append("Some checks failed. Review the tables above before retraining or presenting the project.")

    return "\n".join(lines) + "\n", strict_ok


def main() -> None:
    args = parse_args()
    report, ok = build_report(args)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    output_path = args.output_dir / "reproduction_check.md"
    output_path.write_text(report, encoding="utf-8")
    print(f"Reproduction check written to {output_path.as_posix()}")
    if not ok:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
