from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]

CHECKS = [
    {
        "name": "Compile core scripts and package",
        "command": [
            sys.executable,
            "-m",
            "py_compile",
            "scripts/01_explore_dataset.py",
            "scripts/02_generate_traditional_defects.py",
            "scripts/03_generate_diffusion_defects.py",
            "scripts/05_train_unet_segmentation.py",
            "scripts/13_collect_final_results.py",
            "scripts/14_reproduction_check.py",
            "scripts/14_generate_final_dashboard.py",
            "scripts/15_project_health_check.py",
            "src/industrial_defect/config.py",
            "src/industrial_defect/final_results.py",
            "src/industrial_defect/io.py",
            "src/industrial_defect/paths.py",
        ],
    },
    {
        "name": "Run unit tests",
        "command": [sys.executable, "-m", "pytest", "-q"],
    },
    {
        "name": "Collect final metrics",
        "command": [sys.executable, "scripts/13_collect_final_results.py"],
    },
    {
        "name": "Generate final dashboard",
        "command": [sys.executable, "scripts/14_generate_final_dashboard.py"],
    },
    {
        "name": "Run collect-only reproduction check",
        "command": [sys.executable, "scripts/14_reproduction_check.py"],
    },
]

FORBIDDEN_PATTERNS = ["C:\\Users", "D:\\miniforge", "昂坤视觉", "Desktop"]
SCAN_PATHS = ["README.md", "scripts", "src", "configs", "tests", ".github"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run lightweight project health checks without retraining models.")
    parser.add_argument("--output-dir", type=Path, default=Path("outputs") / "final_report")
    return parser.parse_args()


def run_command(command: list[str]) -> tuple[bool, str]:
    completed = subprocess.run(
        command,
        cwd=PROJECT_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    return completed.returncode == 0, completed.stdout.strip()


def display_command(command: list[str]) -> str:
    if command and Path(command[0]).name.lower().startswith("python"):
        command = ["python", *command[1:]]
    return " ".join(command)


def scan_forbidden_paths() -> tuple[bool, str]:
    findings: list[str] = []
    for root in SCAN_PATHS:
        path = PROJECT_ROOT / root
        if not path.exists():
            continue
        files = [path] if path.is_file() else [item for item in path.rglob("*") if item.is_file()]
        for file_path in files:
            if any(part in {".git", "__pycache__"} for part in file_path.parts):
                continue
            if file_path.name == "15_project_health_check.py":
                continue
            try:
                text = file_path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            for pattern in FORBIDDEN_PATTERNS:
                if pattern in text:
                    findings.append(f"{file_path.relative_to(PROJECT_ROOT).as_posix()}: contains {pattern}")
    return not findings, "\n".join(findings) if findings else "No local absolute paths found."


def main() -> None:
    args = parse_args()
    rows: list[dict[str, str]] = []

    for check in CHECKS:
        ok, output = run_command(check["command"])
        rows.append({
            "name": check["name"],
            "status": "PASS" if ok else "FAIL",
            "command": display_command(check["command"]),
            "output": output,
        })

    ok, output = scan_forbidden_paths()
    rows.append({
        "name": "Scan public files for local absolute paths",
        "status": "PASS" if ok else "FAIL",
        "command": "internal scan",
        "output": output,
    })

    lines = [
        "# Project Health Check",
        "",
        "Generated by `scripts/15_project_health_check.py`.",
        "",
        "| check | status |",
        "| --- | --- |",
    ]
    for row in rows:
        lines.append(f"| {row['name']} | {row['status']} |")
    lines.extend(["", "## Details", ""])
    for row in rows:
        lines.extend([
            f"### {row['name']}",
            "",
            f"Status: `{row['status']}`",
            "",
            f"Command: `{row['command']}`",
            "",
            "```text",
            row["output"] or "(no output)",
            "```",
            "",
        ])

    args.output_dir.mkdir(parents=True, exist_ok=True)
    output_path = args.output_dir / "project_health_check.md"
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Project health check written to {output_path.as_posix()}")

    if any(row["status"] != "PASS" for row in rows):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
