from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = PROJECT_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from industrial_defect.config import defect_types_for_category, supported_categories  # noqa: E402


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run a lightweight U-Net inference demo or validate the deployment interface."
    )
    parser.add_argument("--category", default="tile", choices=supported_categories())
    parser.add_argument("--image", type=Path, help="Input inspection image for local inference.")
    parser.add_argument("--checkpoint", type=Path, help="Local LightUNet checkpoint, usually best_model.pt.")
    parser.add_argument("--output-dir", type=Path, default=Path("outputs") / "demo_inference")
    parser.add_argument("--image-size", type=int, default=256)
    parser.add_argument("--threshold", type=float, default=0.5)
    parser.add_argument("--device", default="auto", help="auto, cpu, cuda, or another torch device string.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate the public inference interface without requiring torch, a checkpoint, or an image.",
    )
    return parser.parse_args(argv)


def validate_args(args: argparse.Namespace) -> None:
    if not 0.0 < args.threshold < 1.0:
        raise ValueError("--threshold must be between 0 and 1.")
    if args.image_size <= 0:
        raise ValueError("--image-size must be positive.")
    if args.dry_run:
        return
    if args.image is None:
        raise FileNotFoundError("--image is required unless --dry-run is set.")
    if args.checkpoint is None:
        raise FileNotFoundError("--checkpoint is required unless --dry-run is set.")
    if not args.image.exists():
        raise FileNotFoundError(f"Input image not found: {args.image}")
    if not args.checkpoint.exists():
        raise FileNotFoundError(
            f"Checkpoint not found: {args.checkpoint}\n"
            "Trained checkpoints are intentionally not committed to this repository. "
            "Re-run a final training command or provide a local best_model.pt."
        )


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def build_dry_run_report(args: argparse.Namespace) -> str:
    defect_types = ", ".join(defect_types_for_category(args.category, evaluation_order=True))
    lines = [
        "# Inference Demo Dry Run",
        "",
        f"Generated at: `{datetime.now().isoformat(timespec='seconds')}`",
        "",
        "This dry run validates the public inference interface without loading a model checkpoint.",
        "",
        "## Selected Configuration",
        "",
        f"- Category: `{args.category}`",
        f"- Defect types: `{defect_types}`",
        f"- Image size: `{args.image_size}`",
        f"- Threshold: `{args.threshold:.2f}`",
        f"- Output directory: `{args.output_dir.as_posix()}`",
        "",
        "## Local Inference Command",
        "",
        "```powershell",
        "python scripts/18_inference_demo.py "
        f"--category {args.category} "
        "--image path/to/inspection_image.png "
        "--checkpoint path/to/best_model.pt "
        "--output-dir outputs/demo_inference",
        "```",
        "",
        "## Expected Outputs",
        "",
        "- `probability_mask.png`: grayscale probability map.",
        "- `binary_mask.png`: thresholded defect mask.",
        "- `overlay.png`: image overlay for quick visual inspection.",
        "- `metadata.json`: input paths, category, threshold, image score, and output paths.",
        "",
        "## Repository Policy",
        "",
        "Model checkpoints and prediction images are local runtime artifacts and are not committed.",
    ]
    return "\n".join(lines)


def build_deployment_readiness_report() -> str:
    lines = [
        "# Deployment Readiness",
        "",
        "Generated by `scripts/18_inference_demo.py --dry-run`.",
        "",
        "| item | status | note |",
        "| --- | --- | --- |",
        "| Training and evaluation results | READY | Final metrics are collected in `outputs/final_report/`. |",
        "| Reproduction package | READY | Config files, tests, CI, and health checks are included. |",
        "| Diagnostic evidence | READY | Distribution repair, threshold, and postprocess summaries are available. |",
        "| Inference interface | READY | `scripts/18_inference_demo.py` supports dry-run and local checkpoint modes. |",
        "| Model checkpoint release | LOCAL ONLY | Checkpoints are intentionally ignored and must be supplied by the user. |",
        "| Production deployment | NOT INCLUDED | The project provides a research demo, not a packaged service. |",
        "",
        "The repository is suitable for result review, reproduction checks, and local inference experiments. "
        "A production system would still need model versioning, runtime monitoring, and integration with the target inspection line.",
    ]
    return "\n".join(lines)


def write_dry_run_outputs(args: argparse.Namespace) -> None:
    validate_args(args)
    write_text(args.output_dir / "demo_requirements.md", build_dry_run_report(args))
    write_text(PROJECT_ROOT / "outputs" / "final_report" / "deployment_readiness.md", build_deployment_readiness_report())
    print(f"Inference dry run written to {(args.output_dir / 'demo_requirements.md').as_posix()}")
    print("Deployment readiness written to outputs/final_report/deployment_readiness.md")


def import_runtime_dependencies():
    try:
        import numpy as np
        import torch
        from PIL import Image
        from industrial_defect.models import load_light_unet_checkpoint
        from industrial_defect.vision import (
            binary_mask_from_probability,
            predict_probability,
            save_binary_mask,
            save_overlay,
            save_probability_mask,
        )
    except ImportError as exc:
        raise ImportError(
            "Local inference requires torch, torchvision, numpy, pillow, and the industrial_defect package. "
            "Install the training requirements or run with --dry-run."
        ) from exc
    return (
        np,
        torch,
        Image,
        load_light_unet_checkpoint,
        binary_mask_from_probability,
        predict_probability,
        save_binary_mask,
        save_overlay,
        save_probability_mask,
    )


def resolve_device(requested: str, torch) -> str:
    if requested == "auto":
        return "cuda" if torch.cuda.is_available() else "cpu"
    return requested


def save_prediction_outputs(args: argparse.Namespace) -> None:
    validate_args(args)
    (
        np,
        torch,
        Image,
        load_light_unet_checkpoint,
        binary_mask_from_probability,
        predict_probability,
        save_binary_mask,
        save_overlay,
        save_probability_mask,
    ) = import_runtime_dependencies()
    device = resolve_device(args.device, torch)
    model = load_light_unet_checkpoint(args.checkpoint, device)

    image = Image.open(args.image).convert("RGB")
    original_size = image.size
    prob = predict_probability(model, args.image, args.image_size, device)
    binary = binary_mask_from_probability(prob, args.threshold)
    args.output_dir.mkdir(parents=True, exist_ok=True)

    probability_path = args.output_dir / "probability_mask.png"
    binary_path = args.output_dir / "binary_mask.png"
    overlay_path = args.output_dir / "overlay.png"
    metadata_path = args.output_dir / "metadata.json"
    save_probability_mask(prob, probability_path, size=original_size)
    save_binary_mask(binary, binary_path, size=original_size)
    save_overlay(args.image, binary, overlay_path, output_size=original_size, color=(255, 40, 40), alpha=0.55)

    metadata = {
        "category": args.category,
        "defect_types": defect_types_for_category(args.category, evaluation_order=True),
        "image_path": str(args.image),
        "checkpoint_path": str(args.checkpoint),
        "image_size": args.image_size,
        "threshold": args.threshold,
        "device": device,
        "image_score": float(prob.max()),
        "defect_area_ratio": float(binary.mean()),
        "outputs": {
            "probability_mask": probability_path.as_posix(),
            "binary_mask": binary_path.as_posix(),
            "overlay": overlay_path.as_posix(),
        },
    }
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    print(f"Inference outputs written to {args.output_dir.as_posix()}")


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    if args.dry_run:
        write_dry_run_outputs(args)
    else:
        save_prediction_outputs(args)


if __name__ == "__main__":
    main()
